### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by sadleb** [thewoolleyman/honeycomb-rails-fullstack-tracing#1]
Hi @thewoolleyman, would it be possible to add the MIT licenses to this repo? I need to do something very similar to what this sample app shows and would love to adapt some of the code. With no license set I don't think I'm legally allowed to do that. Thanks in advance! - Brian Sadler

**Comment by thewoolleyman** [comment]
It currently uses UNLICENSE, which means you can do whatever you want with it :)

https://github.com/thewoolleyman/honeycomb-react-rails-fullstack-tracing/blob/master/LICENSE
